# Generated by Django 5.0.2 on 2024-02-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('add_product', 'Can add products')]},
        ),
    ]
