# Generated by Django 5.0.2 on 2024-02-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_productsnames_productsname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsname',
            old_name='name',
            new_name='nameOfProducts',
        ),
    ]
