# Generated by Django 5.0.2 on 2024-02-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_rename_name_productsname_nameofproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='user',
        ),
    ]
