# Generated by Django 5.0.2 on 2024-03-02 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_batch_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
